/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv functions/worker-configuration.d.ts` (hash: befc01d41be9d34673b6ec2597e44d27)
interface __BaseEnv_CloudflareEnv {
	DB: D1Database;
	PUBLIC_TURNSTILE_SITE_KEY: "0x4AAAAAAD6w9UHtQbh0G61b";
	TURNSTILE_HOSTNAMES: "puck-no.pages.dev,www.puck.no,puck.no";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_TURNSTILE_SITE_KEY" | "TURNSTILE_HOSTNAMES">> {}
}
