-- Phase 3: tournament registrations.
-- Seed data (the 132 pre-migration registrations) is NOT a migration; it is
-- generated by scripts/seed-d1.mjs and applied separately (see README.md).

CREATE TABLE IF NOT EXISTS registrations (
  id INTEGER PRIMARY KEY,
  tournament_slug TEXT NOT NULL,
  type TEXT CHECK(type IN ('player','team')),
  name TEXT NOT NULL,
  country TEXT,
  email TEXT NOT NULL,
  phone TEXT,
  world_ranking INTEGER,
  created_at TEXT DEFAULT (datetime('now'))
);

-- Guard against duplicate registrations: same tournament + type + email
-- (case-insensitive). The POST endpoint maps a violation to 409.
CREATE UNIQUE INDEX IF NOT EXISTS registrations_unique_entry
  ON registrations (tournament_slug, type, lower(email));
