#!/usr/bin/env node
/**
 * Generates seed SQL for the registrations table from
 * src/data/registrations-snapshot.json (the 132 pre-migration registrations
 * scraped from the old Wix site).
 *
 * The old site never published emails/phones, so seeded rows get
 * DETERMINISTIC placeholder emails (seed-<slug>-<n>@seed.puck.no) — they
 * satisfy NOT NULL + the unique guard and are easy to recognise. Real
 * emails/phones were NOT migratable (export from Wix before cancellation
 * if needed). type is 'player' for all seeded rows.
 *
 * Usage:
 *   node scripts/seed-d1.mjs > /tmp/seed.sql
 *   npx wrangler d1 execute DB --local  --file=/tmp/seed.sql   # local dev
 *   npx wrangler d1 execute DB --remote --file=/tmp/seed.sql   # production
 */
import { readFileSync } from 'node:fs';

const snapshot = JSON.parse(
  readFileSync(new URL('../src/data/registrations-snapshot.json', import.meta.url), 'utf8'),
);

const esc = (s) => `'${String(s).replaceAll("'", "''")}'`;

const lines = [
  '-- Generated by scripts/seed-d1.mjs from src/data/registrations-snapshot.json',
  `-- Snapshot date: ${snapshot.snapshot_date}. Placeholder emails — see script header.`,
  'DELETE FROM registrations;', // idempotent re-seed
];

let count = 0;
for (const [slug, players] of Object.entries(snapshot.tournaments)) {
  players.forEach((p, i) => {
    const n = i + 1;
    const email = `seed-${slug}-${n}@seed.puck.no`;
    const raw = p.world_ranking;
    const wrNum = raw != null && raw !== '' && raw !== 'null' ? Number(raw) : NaN;
    const wr = Number.isFinite(wrNum) ? wrNum : null;
    lines.push(
      `INSERT INTO registrations (tournament_slug, type, name, country, email, phone, world_ranking) VALUES (` +
        `${esc(slug)}, 'player', ${esc(p.name)}, ${p.country ? esc(p.country) : 'NULL'}, ` +
        `${esc(email)}, NULL, ${wr ?? 'NULL'});`,
    );
    count++;
  });
}

console.log(lines.join('\n'));
console.error(`seed-d1: generated ${count} rows for ${Object.keys(snapshot.tournaments).length} tournaments`);
