/**
 * Tournament config shared by the API functions.
 * GENERATED by scripts/gen-tournament-config.mjs from the tournaments
 * content collection — do not edit tournament-config.json by hand.
 */
import config from './tournament-config.json';

export interface TournamentConfig {
  /** Min players per team (null = individual tournament). */
  teamMin: number | null;
  /** Max players per team (null = individual tournament). */
  teamMax: number | null;
}

export const TOURNAMENTS = config as unknown as Record<string, TournamentConfig>;

export const KNOWN_SLUGS: ReadonlySet<string> = new Set(Object.keys(TOURNAMENTS));

export function isTeamTournament(slug: string): boolean {
  const c = TOURNAMENTS[slug];
  return c != null && c.teamMin != null;
}
